### ISSUE TITLE
Can't configure `postcss-mixins` plugin 

### ISSUE THREAD

**Issue by m-a-rahal-os** [mantinedev/postcss-preset-mantine#11]
## Issue description
I've been trying to configure [postcss-mixins](https://github.com/postcss/postcss-mixins) plugin for hours now, it just refuses to work while mantine plugin is active. [postcss-preset-mantine](https://github.com/mantinedev/postcss-preset-mantine)

I've created [a repo](https://github.com/m-a-rahal-os/issue-mantine-postcss-mixins) to explain what all what I tried.
Here's a summary of what I tried, all these attempts correspond to a commit in the repo (❌ failed, ✅ worked):
1. ❌ Defining mixins in directory
2. ❌ Defining mixins in postcss.config.js file
2. ❌ Place `postcss-mixins` before `postcss-preset-mantine` -> this causes mantine's mixins to fail (undefined error)
3. ❌ Explicitly install `postcss-mixins` plugin.
4. ✅ Disable `mixins` feature -> All my defined mixins work, but I can't use mantine's mixins :'[

**Comment by rtivital** [comment]
https://mantine.dev/styles/postcss-preset/#custom-mixins
